### PR TITLE
Update for Elemental 4.0.0

### PR DESCRIPTION
**Pull request by obj63mc**
Elemental is now at v4.0 so setting up to let that be installed

### CODE REVIEW

**Comment by jsirish** [comment]
Thanks @obj63mc for the PR! We'll work on getting this merged in by the end of the week. 

Could you adjust to only require Elemental `^4.0@dev`? We're going to roll these updates as a new major version.

**Comment by obj63mc** [comment]
You should be all set now

**Comment by jsirish** [comment]
Thanks for making that change.

It looks like some additional files snuck into the PR, could you zap the vendor folder from the PR?

https://github.com/dynamic/silverstripe-elemental-blog/pull/12/files/97932489aa9aa62b8645e59e7fe7d5fbcdd855e9..fb1c5f2dc79ccd2338188786b54aaa999064463b

I'll be online for a couple more hours and should be able to merge today once it's cleaned up. Thanks!

**Comment by obj63mc** [comment]
Yep, atom autocomplete added that, will push here in one sec.

**Comment by obj63mc** [comment]
You are all set

**Comment by jsirish** [comment]
merged. thanks again @obj63mc

**Pull request merged**
